# RoleBinding: Bind customer-service-role to customer-service-sa (dev)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: customer-service-rolebinding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: customer-service-sa
  namespace: dev
roleRef:
  kind: Role
  name: customer-service-role
  apiGroup: rbac.authorization.k8s.io
---
# RoleBinding: Bind customer-service-role to customer-service-sa (test)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: customer-service-rolebinding
  namespace: test
subjects:
- kind: ServiceAccount
  name: customer-service-sa
  namespace: test
roleRef:
  kind: Role
  name: customer-service-role
  apiGroup: rbac.authorization.k8s.io
---
# RoleBinding: Bind customer-service-role to customer-service-sa (prod)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: customer-service-rolebinding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: customer-service-sa
  namespace: prod
roleRef:
  kind: Role
  name: customer-service-role
  apiGroup: rbac.authorization.k8s.io
