# ServiceAccount for customer-service in dev namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-service-sa
  namespace: dev
---
# ServiceAccount for customer-service in test namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-service-sa
  namespace: test
---
# ServiceAccount for customer-service in prod namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-service-sa
  namespace: prod