# RabbitMQ Credentials Secret
# Contains RabbitMQ connection credentials (base64 encoded)

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: default
type: Opaque
data:
  # echo -n "fintegrate_user" | base64
  RABBITMQ_USER: ZmludGVncmF0ZV91c2Vy
  # echo -n "fintegrate_pass" | base64
  RABBITMQ_PASS: ZmludGVncmF0ZV9wYXNz
